[tool.black]
line-length = 120
target-version = ['py310']
include = '\.py?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''



'''


[tool.isort]
profile = 'black'
line_length = 120