name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run flake8 and reviewdog
        run: |
          reviewdog -reporter=github-check -runners=flake8
          flake8 . | reviewdog -f=pep8 -efm="%f:%l %m" -reporter=github-pr-check
