name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: "testing"
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements-dev.txt

      - name: Create data directory
        run: mkdir -p ./db/data
        working-directory: ${{ github.workspace }}

      - name: Set permissions for data directory
        run: sudo chmod -R 777 ./db/data
        working-directory: ${{ github.workspace }}

      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d
          docker ps

      - name: Run tests
        run: |
          pytest -vv -s
        working-directory: ${{ github.workspace }}

      - name: Stop Docker containers
        run: |
          docker-compose down
